version: '3'

networks:
  sample-network:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    ports:
      - 8888:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - app2
    networks:
      - sample-network

  app:
    build:
      context: .
      dockerfile: ./MediatrPipelinesPlayground/Dockerfile
    ports:
      - 8080:80
      - 8443:443
    depends_on:
      - db
    environment:
      DB_CONNECTION_STRING: "host=db;port=5432;database=fake_database;username=fake_username;password=fake_password"
    networks:
      - sample-network

  auth:
    build:
      context: .
      dockerfile: ./MediatrPipelinesPlayground.Auth/Dockerfile
    ports:
      - 8081:80
      - 8444:443
    networks:
      - sample-network

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "fake_username"
      POSTGRES_PASSWORD: "fake_password"
      POSTGRES_DB: "fake_database"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - sample-network

  cli:
    build:
      context: .
      dockerfile: ./SampleContainerizedWorkerService/Dockerfile
    environment:
      - APP_URL=http:/localhost:80
    ports:
      - 300:300
    networks:
      - sample-network