version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./MediatrPipelinesPlayground/Dockerfile
    ports:
      - 8080:80
      - 8443:443

  app2:
    image: dockersamples/static-site
    ports:
      - 8081:80
      - 8444:443
  
  nginx:
    image: nginx:latest
    ports:
      - 8888:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  cli:
    build:
      context: .
      dockerfile: ./SampleContainerizedWorkerService/Dockerfile
    environment:
      - APP_URL=http:/localhost:80
    ports:
      - 300:300

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=fake_username
      - POSTGRES_PASSWORD=fake_password
      - POSTGRES_DB=fake_database
    volumes:
      - ./pgdata:/var/lib/postgresql/data